name: Build Wheel

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  create:
      tags:
        - '*'

jobs:
  osx:
    runs-on: macos-14

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.12", "3.13"]
        ARCH: ["arm64"]

    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      CXX: clang++
      CC: clang

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.PYTHON_VERSION }}

    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build wheel
      run: |
        set -eux
        pip install delocate
        export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
        if [ ${{ matrix.ARCH }} == "arm64" ]; then
          export _PYTHON_HOST_PLATFORM=macosx-14.0-arm64
          export ARCHFLAGS="-arch arm64"
          export LIBSODIUM_CONFIG_COMMAND="./configure --host=arm64-apple-darwin"
          export OPENSSL_CONFIG_COMMAND="perl Configure darwin64-arm64-cc"
          export DCMAKE_OSX_ARCHITECTURES="arm64"
        fi
        python -m pip install scikit-build
        python -m pip wheel . --verbose -w wheelhouse_dirty
        delocate-wheel -w wheelhouse --require-archs=${{ matrix.arch }} -v wheelhouse_dirty/xeus_python-*.whl

    - name: List wheels
      run: ls wheelhouse

    - uses: actions/upload-artifact@v4
      with:
        name: wheelhouse
        path: wheelhouse/xeus_python-*.whl
        if-no-files-found: error

