name: Build Wheel

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  create:
      tags:
        - '*'

jobs:
  osx:
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.13","3.14"]
        os: [macos-15]

    runs-on: ${{ matrix.os }}

    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      CXX: clang++
      CC: clang

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.PYTHON_VERSION }}

    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4.0'

    - name: Build wheel
      run: |
        set -eux
        ARCH=$(if [ $(uname -p) == 'arm' ]; then echo arm64; else echo x86_64; fi)
        pip install delocate
        export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
        if [ $ARCH == "arm64" ]; then
          export _PYTHON_HOST_PLATFORM=macosx-11.0-arm64
          export ARCHFLAGS="-arch arm64"
          export LIBSODIUM_CONFIG_COMMAND="./configure --host=arm64-apple-darwin"
          export OPENSSL_CONFIG_COMMAND="perl Configure darwin64-arm64-cc"
          export DCMAKE_OSX_ARCHITECTURES="arm64"
        fi
        python -m pip wheel . --verbose -w wheelhouse_dirty
        delocate-wheel -w wheelhouse --require-archs=$ARCH -v wheelhouse_dirty/xeus_python-*.whl

    - name: List wheels
      run: ls wheelhouse

    - uses: actions/upload-artifact@v4
      with:
        name: wheelhouse-${{ matrix.os }}-${{ matrix.PYTHON_VERSION }}
        path: wheelhouse/xeus_python-*.whl
        if-no-files-found: error
